### ISSUE TITLE
equo: --ask should be default, config option

### ISSUE THREAD

**Issue by schnittchen** [Sabayon/entropy#33]
Equo is a dangerous tool without using --ask, in particular `equo remove`.

It would be very useful to have a config option, preferrably defaulting to "yes", having the same effect as passing --ask.

**Comment by optiz0r** [comment]
IMHO, an environment variable akin to `EMERGE_DEFAULT_OPTS` would be a better fit here, as there's no `--dont-ask` parameter that can be used to negate the `--ask` set in the config file otherwise. It's also more flexible to options other than just ask. It would need to be something like `EQUO_INSTALL_OPTS` rather than for all equo commands, since not every subcommand takes an `--ask` parameter.

If anyone wants to make this a default option, it can be put into a file in `/etc/env.d`. To install a package without the default opts from the environment variable, something like `env EQUO_INSTALL_OPTS='' equo install foo` can be used instead.

**Comment by mudler** [comment]
@schnittchen  Thanks for your feedback
In such situations what i tend to do instead is to create system alias functions to specific set/combination of commands that i use daily.

@optiz0r  i don't think that's a feature that should be there, i could think an equivalent to ```EMERGE_DEFAULT_OPTS``` would make sense but not for ```EQUO_INSTALL_OPTS```, that would open then the door to ```EQUO_REMOVE_OPTS```, ```EQUO_SEARCH_OPTS``` and so on with the others equo's commands with the result of just incrementing complexity of code/usage. 

Giving another thought: an ```EQUO_DEFAULT_OPTS``` don't have a lot of sense to me neither, since most of options are already configurable in the client.conf  and the few ones that are not IMHO are not sufficient to promote a global config variable (to cover edge-cases).

going back to the original request, --ask for me shouldn't be default for more than one reasons:

* historically was always like this, and i do not see here a valid reason to break user habits/scripts
* equo mimics the emerge command behavior in regards to that, and it is a plus to me (gentoo users will feel more at home)
* there are other ways you can accomplish the same thing without having it implemented straight into the PM

That being said, an option in the config file to enable that behavour sounds more reasonable to me

**Comment by Darksurf** [comment]
This is what I agree with.
equo mimics the emerge command behavior in regards to that, and it is a plus to me (gentoo users will feel more at home)

**Comment by Enlik** [comment]
I don't think it's going to happen, so I'll close the issue. Please also consider that changing something as important as default --ask may be more dangerous than no default --ask in any case. What if someone thinks --ask is enabled in config, but it's not (for any reason), so types `equo remove blah` and goes to eat supper, comes back and sees no prompt but a bunch of packages removed?

**Comment by Enlik** [comment]
consider that changing → consider that being able to change (in configuration)
